services:
  backend:
    build: .
    # ports:
    #   - "5000:5000"
    restart: unless-stopped
  frontend:
    build: client
    # ports:
    #   - "3000:3000"
    restart: unless-stopped
